FROM python:3.11-slim

WORKDIR /app

COPY backend/flask_app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/flask_app backend/flask_app
COPY frontend frontend

EXPOSE 5000

CMD ["python", "backend/flask_app/app.py"]